Develop
smswithoutborders/blog pull request #14
Opened 2024-04-24 14:50 UTC by mildrette

fix: Added no data available to the release section incase there is no post available

2024-04-24 22:53 UTC, PromiseFru commented
Thank you, @mildrette!

Could you please provide a more descriptive title for your Pull Request?

There seems to be an issue with the `releases` tab, which disrupts the view when clicked.

![image](https://github.com/smswithoutborders/blog/assets/33162641/d8497053-ce03-4be7-be37-b362f4afcd52)

Please take a look at it.

2024-04-24 23:02 UTC, PromiseFru requested changes
Thank you, @mildrette!

Could you please provide a more descriptive title for your Pull Request?

There seems to be an issue with the `releases` tab, which disrupts the view when clicked.

![image](https://github.com/smswithoutborders/blog/assets/33162641/d8497053-ce03-4be7-be37-b362f4afcd52)

Please take a look at it.

2024-04-25 11:15 UTC, PromiseFru commented
Thank you @mildrette!

There are a few more things to address:

- The alignment of the top bar has been distorted on mobile view.

![image](https://github.com/smswithoutborders/blog/assets/33162641/3037b1c2-08d8-4fcb-8489-4665490d2ae3)

- After creating a `_releases` directory, create a release post in the directory. When you click on the post from the release tab, it breaks the view.

![image](https://github.com/smswithoutborders/blog/assets/33162641/66ee4813-f283-4849-ab26-8a358f422f4d)

2024-04-26 10:17 UTC, PromiseFru requested changes
Thank you, @mildrette! Just a few more tweaks 😉

2024-04-26 10:17 UTC, PromiseFru commented on src/app/_components/navbar.tsx
> +					<Logo src="/icon.png" alt="SMSWithoutBorders Logo" name="SWOB" url="/" />
Why change the text here?

2024-04-26 10:17 UTC, PromiseFru commented on src/app/_components/navbar.tsx
> +							<FaEnvelope size={30} className="rounded bg-white p-1" />
Why remove the link `target`?

2024-04-26 10:17 UTC, PromiseFru commented on src/app/_components/navbar.tsx
> +							<FaLinkedin size={30} className="rounded-full bg-white p-1" />
We should ensure that all items have a uniform style, including text size, colours, and effects.

2024-04-26 10:17 UTC, PromiseFru commented on src/app/_components/post-preview.tsx
> +					className="hover:unde/postsrline font-semibold"
```suggestion
					className="hover:underline font-semibold"
```

2024-04-26 10:17 UTC, PromiseFru commented on src/app/_components/navbar.tsx
We should arrange the icons horizontally for the mobile view.

![image](https://github.com/smswithoutborders/blog/assets/33162641/f82d0c69-5cab-4049-8cf6-3800feef0f93)

2024-04-26 11:00 UTC, mildrette commented on src/app/_components/navbar.tsx
all done

2024-04-26 12:02 UTC, PromiseFru submitted a review, later dismissed
Thank you, @mildrette!

2024-04-26 12:46 UTC, merged